version: "3"

services:

  # web:
  #   image: nginx:latest
  #   container_name: web
  #   ports:
  #     - "${WEB_PORT}:${WEB_PORT}"
  #   volumes:
  #     - ./.docker/web/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    container_name: app
    tty: true
    build:
      dockerfile: ./.docker/php/Dockerfile.prod
    ports:
      - "${APP_PORTS}"
    volumes:
      - ./:/var/www/html/app
    working_dir: /var/www/html/app

  db:
    tty: true
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./.docker/db:/var/lib/mysql

  # cache:
  #   image: redis:bookworm
  #   container_name: cache
  #   tty: true
  #   ports:
  #     - "${CACHE_PORT}:${CACHE_PORT}"
  #   restart: always