version: "3"

services:

  # web:
  #   image: nginx:latest
  #   container_name: web
  #   ports:
  #     - "${WEB_PORT}:${WEB_PORT}"
  #   volumes:
  #     - ./.docker/web/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - app_network

  app:
    container_name: app
    tty: true
    build:
      dockerfile: ./.docker/php/Dockerfile.prod
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./:/var/www/html/app
    working_dir: /var/www/html/app
    depends_on:
      - db
      # - cache
      # - web
    networks:
      - app_network

  db:
    image: mysql:latest
    container_name: db
    tty: true
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.docker/db/mysql:/var/lib/mysql
    networks:
      - app_network

  # cache:
  #   image: redis:bookworm
  #   container_name: cache
  #   tty: true
  #   ports:
  #     - "${CACHE_PORT}:${CACHE_PORT}"
  #   restart: always

networks:
  app_network: